version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - ./FrontEnd:/var/www/html

  django:
    build: ./BackEnd
    container_name: django
    ports:
      - "8000"
    tty: true
    stdin_open: true
    restart: on-failure
