version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./.env
    volumes:
      - ./BackEnd/database:/var/lib/postgresql/data
    restart: on-failure
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  django:
    depends_on:
      - db
    build: ./BackEnd
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    tty: true
    stdin_open: true
    volumes:
      - ./BackEnd/storage:/usr/src/app/user_images
    restart: on-failure

  nginx:
    depends_on:
      - django
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - ./FrontEnd:/var/www/html
