version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: 'pong_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"
    volumes:
      - ./BackEnd/db_volume:/var/lib/postgresql/data
    restart: on-failure
  
  django:
    depends_on:
      - db
    build: ./BackEnd
    container_name: django
    ports:
      - "8000"
    tty: true
    stdin_open: true
    restart: on-failure

  nginx:
    depends_on:
      - django
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - ./FrontEnd:/var/www/html
