name: "🐛 Bug "
description: "Bug 발생 시 작성해주세요."
title: "🐛 [Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: 무슨 문제가 발생했는지 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: 이해를 돕기 위해 스크린샷을 첨부해주세요.
  - type: textarea
    id: Expected-Behavior
    attributes:
      label: Expected Behavior
      description: 버그가 없었을 때 어떤 결과가 나왔어야 하는지 설명해주세요.
  - type: textarea
    id: log
    attributes:
      label: Log
      description: 에러 로그를 복사해서 첨부해주세요.
      render: Shell
