name: "⚒ Refactor "
description: "Refactor시 작성해주세요."
title: "⚒ [Refactor] "
labels: ["documentation"]
body:
  - type: textarea
    id: before
    attributes:
      label: Before
      description: 변경 전 코드를 설명해주세요
    validations:
      required: true
  - type: textarea
    id: after
    attributes:
      label: After
      description: 변경 후 코드를 설명해주세요
    validations:
      required: true
  - type: textarea
    id: Expected-Behavior
    attributes:
      label: Expected Behavior
      description: 어떤 결과가 생기는지 설명해주세요.
